name: Terraform Workflow

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the 'main' branch
    workflow_dispatch:  # Optional: for manual testing

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.5'  # Specify the version of Terraform

      - name: Terraform Format Check
        run: terraform fmt -check  # Ensure that the Terraform code is formatted properly

      - name: Terraform Validate
        run: terraform validate  # Validate the Terraform configuration

      - name: Cache Terraform providers
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf', '**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Set up GitHub token as environment variable
        run: echo "GITHUB_TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV  # Make sure the token is accessible

      - name: Terraform Init
        run: terraform init
        working-directory: terraform  # Add this line to specify the correct directory

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform  # Add this line to specify the correct directory

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: terraform  # Add this line to specify the correct directory
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Pass the GitHub token to the Terraform provider
