name: Terraform GitHub Actions Workflow

on:
  workflow_dispatch:  # Optional: for manual testing

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    # Install Terraform providers
    - name: Terraform Init
      working-directory: ./terraform  # Specify the directory where your Terraform configuration is
      run: terraform init

    # Validate the Terraform configuration
    - name: Terraform Validate
      working-directory: ./terraform  # Specify the directory where your Terraform configuration is
      run: terraform validate

    # Apply the Terraform script
    - name: Terraform Apply
      working-directory: ./terraform  # Specify the directory where your Terraform configuration is
      env:
        TOKEN: ${{ secrets.TOKEN }}  # Pass GitHub Token from Secrets
      run: terraform apply -auto-approve
